### ISSUE TITLE
Login Problem....

### ISSUE THREAD

**Issue by Giaky** [1btcxe/wlox#30]
Add username and password for frontend login, and receive a message
"please provide a password"

any solutions?

**Comment by mbassan** [comment]
There are a few possible reasons for your issue:
1) Frontend cannot find the auth repo, or the auth repo is giving an error.
2) You don't have a valid regex pattern in "password regex" in the
backstage2 -> api config (you might consider using the pattern that is
suggested in the manual).
3) You might be missing required PHP modules.

In any case, the first step is to log the PHP errors that are ocurring in
frontend and auth.

Please contact us on Skype at support.wlox if you need further assistance.

On Sat, Sep 5, 2015 at 2:58 AM, Giaky <notifications@github.com> wrote:

> Add username and password for frontend login, and receive a message
> "please provide a password"
>
> any solutions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/1btcxe/wlox/issues/30>.
>



-- 
Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by Giaky** [comment]
1: now check it
2: what are the correct password regex? in the manual not specify the options available.
3: all php modules are installed correct...

**Comment by mbassan** [comment]
It's hard to know exactly what is happening over this forum. If you contact
me tomorrow on Skype, I will help you debug and figure out what is
happening.

On Sun, Sep 6, 2015 at 11:23 AM, Giaky <notifications@github.com> wrote:

> 1: now check it
> 2: what are the correct password regex? in the manual not specify the
> options available.
> 3: all php modules are installed correct...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/1btcxe/wlox/issues/30#issuecomment-138097588>.
>



-- 
Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Comment by Giaky** [comment]
ok, i have send a request on skype

**Comment by ergofobe** [comment]
Closing this due to the issue being related to WLOX deployment and not 1BTCXE specific.
